//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloudflow.Extensions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cloudflow.Extensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks a folder for the existence of files..
        /// </summary>
        internal static string CheckFolderContentDescription {
            get {
                return ResourceManager.GetString("CheckFolderContentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Folder Content.
        /// </summary>
        internal static string CheckFolderContentName {
            get {
                return ResourceManager.GetString("CheckFolderContentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default Cloudflow job..
        /// </summary>
        internal static string DefaultJobDescription {
            get {
                return ResourceManager.GetString("DefaultJobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Job.
        /// </summary>
        internal static string DefaultJobName {
            get {
                return ResourceManager.GetString("DefaultJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name Masks.
        /// </summary>
        internal static string FileNameMasksLabel {
            get {
                return ResourceManager.GetString("FileNameMasksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string FolderLabel {
            get {
                return ResourceManager.GetString("FolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Message.
        /// </summary>
        internal static string LogMessageLabel {
            get {
                return ResourceManager.GetString("LogMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs a message to a file..
        /// </summary>
        internal static string LogStepDescription {
            get {
                return ResourceManager.GetString("LogStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string LogStepName {
            get {
                return ResourceManager.GetString("LogStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A trigger that fires after a certain amount of time has passed..
        /// </summary>
        internal static string TimerTriggerDescription {
            get {
                return ResourceManager.GetString("TimerTriggerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TimerTriggerIcon {
            get {
                object obj = ResourceManager.GetObject("TimerTriggerIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string TimerTriggerName {
            get {
                return ResourceManager.GetString("TimerTriggerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string WatchFolderPathLabel {
            get {
                return ResourceManager.GetString("WatchFolderPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A trigger that fires when files are added, changed or deleted in a folder..
        /// </summary>
        internal static string WatchFolderTriggerDescription {
            get {
                return ResourceManager.GetString("WatchFolderTriggerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Folder.
        /// </summary>
        internal static string WatchFolderTriggerName {
            get {
                return ResourceManager.GetString("WatchFolderTriggerName", resourceCulture);
            }
        }
    }
}
